(define pi 3.141592653589793238)

(define (radyan x)
  (* x (/ pi 180)))

(define (factorial n)
  (if (= n 0)
      1
      (* n (factorial (- n 1)))))

(define (islemsin x n)
     (/ (expt (radyan x) (+ (* 2 n) 1)) (factorial (+ (* 2 n) 1))))

(define (islemcos x n)
     (/ (expt (radyan x) (* 2 n)) (factorial (* 2 n))))

(define (sinh x)
  (+ (islemsin x 0)
     (islemsin x 1)
     (islemsin x 2)
     (islemsin x 3)
     (islemsin x 4)
     (islemsin x 5)
     (islemsin x 6)
     (islemsin x 7)
     (islemsin x 8)
     (islemsin x 9)
     (islemsin x 10)
     (islemsin x 11)
     (islemsin x 12)
     (islemsin x 13)
     (islemsin x 14)
     (islemsin x 15)
     (islemsin x 16)
     (islemsin x 17)
     (islemsin x 18)
     (islemsin x 19)
     (islemsin x 20)
     (islemsin x 21)
     (islemsin x 22)
     (islemsin x 23)
     (islemsin x 24)
     (islemsin x 25)
     (islemsin x 26)
     (islemsin x 27)
     (islemsin x 28)
     (islemsin x 29)
     (islemsin x 30)))

(define (cosh x)
  (+ (islemcos x 0)
     (islemcos x 1)
     (islemcos x 2)
     (islemcos x 3)
     (islemcos x 4)
     (islemcos x 5)
     (islemcos x 6)
     (islemcos x 7)
     (islemcos x 8)
     (islemcos x 9)
     (islemcos x 10)
     (islemcos x 11)
     (islemcos x 12)
     (islemcos x 13)
     (islemcos x 14)
     (islemcos x 15)
     (islemcos x 16)
     (islemcos x 17)
     (islemcos x 18)
     (islemcos x 19)
     (islemcos x 20)
     (islemcos x 21)
     (islemcos x 22)
     (islemcos x 23)
     (islemcos x 24)
     (islemcos x 25)
     (islemcos x 26)
     (islemcos x 27)
     (islemcos x 28)
     (islemcos x 29)
     (islemcos x 30)))
